//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class stp_contact_us
    {
        public int contact_us_id { get; set; }
        public System.Guid contact_us_guid { get; set; }
        public System.DateTime contact_us_timestamp { get; set; }
        public string contact_us_language { get; set; }
        public string contact_us_app_name { get; set; }
        public string contact_us_app_guid { get; set; }
        public string contact_us_app_version { get; set; }
        public string contact_us_user_fname { get; set; }
        public string contact_us_user_surname { get; set; }
        public string contact_us_user_email { get; set; }
        public string contact_us_subject { get; set; }
        public string contact_us_message { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class stp_download_counter
    {
        public int dwnld_cntr_id { get; set; }
        public int dwnld_cntr_downloads_total { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class stp_try01_for_free_win
    {
        public int try01_win_id { get; set; }
        public System.Guid try01_win_guid { get; set; }
        public System.DateTime try01_win_timestamp { get; set; }
        public string try01_win_language { get; set; }
        public string try01_win_app_name { get; set; }
        public string try01_win_app_guid { get; set; }
        public string try01_win_app_version { get; set; }
        public string try01_win_user_fname { get; set; }
        public string try01_win_user_surname { get; set; }
        public string try01_win_user_email { get; set; }
    }
}
namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class stp_try02_for_free_mac
    {
        public int try02_mac_id { get; set; }
        public System.Guid try02_mac_guid { get; set; }
        public System.DateTime try02_mac_timestamp { get; set; }
        public string try02_mac_language { get; set; }
        public string try02_mac_app_name { get; set; }
        public string try02_mac_app_guid { get; set; }
        public string try02_mac_app_version { get; set; }
        public string try02_mac_user_fname { get; set; }
        public string try02_mac_user_surname { get; set; }
        public string try02_mac_user_email { get; set; }
    }
}
