//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SortThosePicsEntities : DbContext
    {
        public SortThosePicsEntities()
            : base("name=SortThosePicsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<stp_download_counter> stp_download_counter { get; set; }
        public virtual DbSet<stp_try01_for_free_win> stp_try01_for_free_win { get; set; }
        public virtual DbSet<stp_try02_for_free_mac> stp_try02_for_free_mac { get; set; }
        public virtual DbSet<stp_contact_us> stp_contact_us { get; set; }
    }
}
